- hosts: masters
  remote_user: root

  vars:
    master_config : /etc/origin/master/master-config.yaml
    htpasswd : /etc/origin/master/htpasswd
    admin_user : oscadm
    admin_passwd : r3dh4t1!
    users: 
       - { name: "{{ admin_user }}" , passwd: "{{ admin_passwd }}" }
       - { name: 'openshift-dev', passwd : 'devel' }
    coolstore_demo : https://github.com/redhatdemocentral/rhcs-coolstore-demo/archive/master.zip

  tasks:
  - name: install httpd-tools (htpasswd)
    yum: name=httpd-tools state=latest

  - name: Create HtPasswd File
    file: path={{ htpasswd }} state=touch mode="u=rw,g=r,o=r"
    
  - name: Create User
    shell: htpasswd -b {{ htpasswd }} {{ item.name }} {{ item.passwd }}
    with_items: "{{ users }}"

  - name: Add cluster-admin to {{ admin_user }}
    shell: "oadm policy add-cluster-role-to-user cluster-admin {{ admin_user }}"

  - name: Install packages
    yum: name={{ item }} state=present
    with_items:
      - unzip

  - name: Get coolstore-demo
    shell: wget {{ coolstore_demo }}

  - name: unzip coolstore-demo
    shell : unzip master.zip

